#!/bin/bash

daemon_name=uploadServer

. /etc/rc.conf
. /etc/rc.d/functions
. /etc/conf.d/$daemon_name.conf

case "$1" in
	start)
		stat_busy "Starting $daemon_name daemon"
    
    if [ ! -z "$PORT" ]; then
      opts="$opts -p $PORT"
    fi;
    if [ ! -z "$ADDRESS" ]; then
      opts="$opts -a $ADDRESS"
    fi;
    if [ ! -z "$FORM_URL" ]; then
      opts="$opts -f $FORM_URL"
    fi;
    if [ ! -z "$BUFFER_SIZE" ]; then
      opts="$opts --buffer-size=$BUFFER_SIZE"
    fi;
    if [ ! -z "$UPLOAD_FOLDER" ]; then
      opts="$opts -u $UPLOAD_FOLDER"
    fi;
    if [ "$ENABLE_PROGRESS" == "True" ]; then
      opts="$opts --enable-progress"
    fi;
    if [ ! -z "$SESSION_KEY" ]; then
      opts="$opts --session-key=$SESSION_KEY"
    fi;
		# RUN
		${daemon_name} ${opts} >i /dev/null  2>> /var/log/uploadserver.log &
    PID=$!

    sleep 1
		if [[ $(ps -p $PID | wc -l) -lt 2 ]]; then
			stat_fail
			exit 1
		else
			echo -n $PID > /var/run/$daemon_name.pid
			add_daemon $daemon_name
			stat_done
		fi
		;;

	stop)
		stat_busy "Stopping $daemon_name daemon"
    if [ ! -f /var/run/$daemon_name.pid ]; then
      stat_fail
      exit 1
    fi
		PID=$(cat /var/run/$daemon_name.pid)
		# KILL
		[[ -n $PID ]] && kill $PID &> /dev/null

		if [[ $? -gt 0 ]]; then
			stat_fail
			exit 1
		else
      rm -f /var/run/$daemon_name.pid &> /dev/null
			rm_daemon $daemon_name
			stat_done
		fi
		;;

	restart)
		$0 stop
		sleep 3
		$0 start
		;;

	status)
		stat_busy "Checking $daemon_name status";
		ck_status $daemon_name
		;;

	*)
		echo "usage: $0 {start|stop|restart|status}"
esac

exit 0

# vim:set ts=2 sw=2 et:
